### ISSUE TITLE
Typo in database permissions

### ISSUE THREAD

**Issue by pripatelUK** [status-im/infra-role-postgres-ha#10]
Please fix the database permission error caused by the typo "DATABSE"

https://github.com/status-im/infra-role-postgres-ha/blame/20d3d9dccf54eda23068dc1efc765e9a66eb4cea/templates/init/databases.sql#L26

**Comment by jakubgs** [comment]
Fixed:

- [`infra-role-postgres-ha#aa6b4fe5`](https://github.com/status-im/infra-role-postgres-ha/commit/aa6b4fe5) - init: add support for creating extra users
